typography_spectrum: 0.1419512601740806
color:
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
  brandStrength: 0.1646430960629541
  lightness: 0.1777561896944437
  saturation: 0.21132989062060886
  rhythmicContrast: 0.6362309722923258
github: true
layout_spectrum: 0.12863200807621203
analytics:
  google: UA-97246733-1
author:
  name: Admin
  email: info@clockd.com
logo: null
name: Clock'd
url: 'http://clockd.com'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
title: Clock'd
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://static1.squarespace.com/static/51a382c0e4b00f442893a723/t/54cc1f8ae4b008593cca317b/1422663564366/madeinmoments.bratislava.hipster">
    src: >-
      https://static1.squarespace.com/static/51a382c0e4b00f442893a723/t/54cc1f8ae4b008593cca317b/1422663564366/madeinmoments.bratislava.hipster
    metadata:
      datePublished: null
      isBasedOnUrl: >-
        https://static1.squarespace.com/static/51a382c0e4b00f442893a723/t/54cc1f8ae4b008593cca317b/1422663564366/madeinmoments.bratislava.hipster
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://static1.squarespace.com'
        name: Squarespace
        favicon: null
        domain: static1.squarespace.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Getting a job shouldn't be a job
purpose:
  - type: external
    label: Looking For A Job?
    url: 'https://form.jotform.us/70904635618157'
  - type: external
    label: Looking To Fill A Job?
    url: 'https://form.jotform.us/71078036884160'
